@extends('layouts.admin')
@section('title', 'Perusahaan & Pengaturan')
@section('content')
<div class="admin-heading"><h1>Perusahaan & Pengaturan</h1></div><form enctype="multipart/form-data" method="post" action="{{ route('admin.settings.update') }}" class="editor-form" data-submit-form>@csrf @method('PUT')
<section class="form-section"><h2>Profil Perusahaan</h2><x-field name="company_logo" type="file" label="Logo perusahaan (JPG, PNG, WebP; maks. 4 MB)" accept=".jpg,.jpeg,.png,.webp"/><x-field name="company_name" label="Nama perusahaan" :value="$settings['company_name']" required/><x-field name="tagline" label="Tagline" :value="$settings['tagline']" required/><x-field name="profile" label="Profil perusahaan" type="textarea" :value="$settings['profile']" rows="6"/></section>
<section class="form-section"><h2>Kontak</h2><x-field name="address" label="Alamat" type="textarea" :value="$settings['address']"/><div class="form-grid"><x-field name="phone" label="Telepon" :value="$settings['phone']" required/><x-field name="whatsapp_number" label="WhatsApp (format 628...)" :value="$settings['whatsapp_number']"/><x-field name="email" type="email" label="Email publik" :value="$settings['email']" required/><x-field name="sales_email" type="email" label="Email sales" :value="$settings['sales_email']"/></div><x-field name="inquiry_email" type="email" label="Email penerima inquiry" :value="$settings['inquiry_email']" required/><x-field name="map_url" type="url" label="Link peta" :value="$settings['map_url']"/></section>
<section class="form-section"><h2>Informasi Legal</h2><x-field name="legal_information" label="Informasi yang disetujui untuk publik" type="textarea" :value="$settings['legal_information']" rows="5"/></section>
<section class="form-section"><h2>SEO Default</h2><x-field name="meta_title" label="Title" :value="$settings['meta_title']" required maxlength="200"/><x-field name="meta_description" label="Description" type="textarea" :value="$settings['meta_description']" required maxlength="500"/></section><button class="button"><x-icon name="save"/>Simpan Pengaturan</button></form>
@endsection
