<?php

return [
    [
        'id' => 'engineering',
        'number' => '01',
        'navLabel' => 'Engineering',
        'eyebrow' => 'ENGINEERING',
        'title' => ['Engineering Solutions', 'for Industrial Excellence.'],
        'description' => 'Solusi engineering terintegrasi untuk mendukung keandalan, efisiensi, dan kebutuhan operasional industri.',
        'image' => 'images/industrial.jpg',
        'width' => 1920, 'height' => 1280,
        'position' => 'center', 'mobilePosition' => '58% center',
    ],
    [
        'id' => 'mechanical',
        'number' => '02',
        'navLabel' => 'Mechanical',
        'eyebrow' => 'MECHANICAL',
        'title' => ['Reliable Mechanical', 'Solutions for Industry.'],
        'description' => 'Solusi mekanikal, equipment, dan spare parts untuk mendukung performa dan keandalan operasional industri.',
        'image' => 'images/hero-pumps.webp',
        'width' => 1672, 'height' => 941,
        'position' => 'center', 'mobilePosition' => '68% center',
    ],
    [
        'id' => 'electrical',
        'number' => '03',
        'navLabel' => 'Electrical',
        'eyebrow' => 'ELECTRICAL',
        'title' => ['Powering Reliable', 'Industrial Operations.'],
        'description' => 'Solusi dan kebutuhan electrical untuk mendukung sistem industri yang aman, stabil, dan andal.',
        'image' => 'images/hero/electrical.webp',
        'width' => 1672, 'height' => 941,
        'position' => 'center', 'mobilePosition' => '65% center',
    ],
    [
        'id' => 'instrumentation',
        'number' => '04',
        'navLabel' => 'Instrumentation',
        'eyebrow' => 'INSTRUMENTATION',
        'title' => ['Precision Control', 'for Industrial Performance.'],
        'description' => 'Solusi instrumentation dan control untuk meningkatkan akurasi, monitoring, dan efisiensi proses industri.',
        'image' => 'images/hero/instrumentation.webp',
        'width' => 1672, 'height' => 941,
        'position' => 'center', 'mobilePosition' => '75% center',
    ],
    [
        'id' => 'oil-spill-response',
        'number' => '05',
        'navLabel' => 'Oil Spill Response & Prevention',
        'eyebrow' => 'OIL SPILL RESPONSE & PREVENTION',
        'title' => ['Prepared to Protect.', 'Ready to Respond.'],
        'description' => 'Solusi penanganan dan pencegahan tumpahan minyak untuk mendukung operasi yang aman dan bertanggung jawab.',
        'image' => 'images/hero/oil-spill-response.webp',
        'width' => 1672, 'height' => 941,
        'position' => 'center', 'mobilePosition' => '70% center',
    ],
];
