@extends('layouts.admin')
@section('title', ($entry->exists ? 'Edit ' : 'Tambah ').$config['label'])
@section('content')
<div class="admin-heading"><div><a class="text-link" href="{{ route('admin.catalog.index', $module) }}"><x-icon name="arrow-left"/>{{ $config['label'] }}</a><h1>{{ $entry->exists ? 'Edit' : 'Tambah' }} {{ $config['label'] }}</h1></div></div>
<form method="post" enctype="multipart/form-data" action="{{ $entry->exists ? route('admin.catalog.update', [$module, $entry->id]) : route('admin.catalog.store', $module) }}" class="editor-form" data-submit-form>@csrf @if($entry->exists)@method('PUT')@endif
<section class="form-section"><h2>Informasi Utama</h2><div class="form-grid"><x-field name="name" label="Nama" :value="$entry->name" required maxlength="200" data-slug-source/><x-field name="slug" label="Slug URL" :value="$entry->slug" required maxlength="200" pattern="[a-z0-9]+(-[a-z0-9]+)*" data-slug-target/></div>
@if($module === 'products')<div class="form-grid"><div class="field"><label for="category_id">Kategori *</label><select name="category_id" id="category_id" required><option value="">Pilih kategori</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $entry->category_id) == $category->id)>{{ $category->name }}</option>@endforeach</select></div><div class="field"><label for="brand_id">Brand *</label><select name="brand_id" id="brand_id" required><option value="">Pilih brand</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(old('brand_id', $entry->brand_id) == $brand->id)>{{ $brand->name }}</option>@endforeach</select></div></div><x-field name="model_or_series" label="Model / Seri" :value="$entry->model_or_series"/><x-field name="short_description" label="Ringkasan" type="textarea" :value="$entry->short_description" required maxlength="1000"/>@endif
<x-field name="description" label="Deskripsi" type="textarea" :value="$entry->description" rows="5"/>
@if($module === 'brands')<x-field name="focus" label="Fokus teknologi" :value="$entry->focus"/><x-field name="website_url" label="Website principal" type="url" :value="$entry->website_url"/>@endif
@if($module === 'industries')<x-field name="challenges" label="Kebutuhan / tantangan" type="textarea" :value="$entry->challenges"/><x-field name="solution_copy" label="Solusi" type="textarea" :value="$entry->solution_copy"/>@endif
</section>
@if($module === 'industries')<section class="form-section"><h2>Produk Terkait</h2>@foreach($products as $product)<label class="check-field"><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" @checked(in_array($product->id, old('product_ids', !session()->hasOldInput() && $entry->exists ? $entry->products->pluck('id')->all() : [])))>{{ $product->name }}</label>@endforeach</section>@endif
@if($module === 'products')<section class="form-section"><h2>Detail Teknis</h2><div class="form-grid"><x-field name="benefits_text" label="Keunggulan (satu per baris)" type="textarea" :value="implode(PHP_EOL, $entry->benefits ?? [])"/><x-field name="applications_text" label="Aplikasi (satu per baris)" type="textarea" :value="implode(PHP_EOL, $entry->applications ?? [])"/></div><h3>Spesifikasi</h3><div id="specifications">@foreach(old('specifications', $entry->specifications ?: [['label' => '', 'value' => '']]) as $index => $spec)<div class="spec-row"><div class="field"><label for="spec-label-{{ $index }}">Parameter</label><input id="spec-label-{{ $index }}" name="specifications[{{ $index }}][label]" value="{{ $spec['label'] ?? '' }}" maxlength="150"></div><div class="field"><label for="spec-value-{{ $index }}">Nilai</label><input id="spec-value-{{ $index }}" name="specifications[{{ $index }}][value]" value="{{ $spec['value'] ?? '' }}" maxlength="500"></div><button type="button" class="icon-button danger" data-remove-spec title="Hapus spesifikasi" aria-label="Hapus spesifikasi"><x-icon name="trash-2"/></button></div>@endforeach</div><button type="button" class="button secondary small" data-add-spec><x-icon name="plus"/>Tambah Spesifikasi</button><fieldset class="industry-options"><legend>Industri terkait</legend>@foreach($industries as $industry)<label class="check-field"><input type="checkbox" name="industry_ids[]" value="{{ $industry->id }}" @checked(in_array($industry->id, old('industry_ids', !session()->hasOldInput() && $entry->exists ? $entry->industries->pluck('id')->all() : [])))>{{ $industry->name }}</label>@endforeach</fieldset></section>@endif
<section class="form-section"><h2>Media</h2>@if($entry->image)<img class="admin-preview" src="{{ $entry->image_url }}" alt="Gambar saat ini" width="180" height="140">@if(in_array($module, ['products', 'brands'], true))<label class="check-field"><input type="checkbox" name="remove_image" value="1">{{ $module === 'brands' ? 'Hapus logo' : 'Hapus gambar utama' }}</label>@endif @endif<x-field name="image" label="Gambar / logo (JPG, PNG, WebP; maks. 4 MB)" type="file" accept=".jpg,.jpeg,.png,.webp"/><x-field name="image_alt" label="Teks alternatif gambar" :value="$entry->image_alt"/>
@if($module === 'products')<x-field name="gallery[]" label="Tambah galeri (maks. 8 gambar per unggahan)" type="file" multiple accept=".jpg,.jpeg,.png,.webp"/><div class="gallery">@foreach($entry->gallery ?? [] as $path)<label><img class="admin-preview" src="{{ asset('storage/'.$path) }}" alt="Gambar galeri" width="120" height="100"><span class="check-field"><input type="checkbox" name="remove_gallery[]" value="{{ $path }}">Hapus</span></label>@endforeach</div><x-field name="datasheet_file" label="Datasheet (PDF; maks. 10 MB)" type="file" accept=".pdf"/>@if($entry->datasheet_file)<a class="text-link" href="{{ asset('storage/'.$entry->datasheet_file) }}" target="_blank" rel="noopener"><x-icon name="download"/>Lihat Datasheet</a><label class="check-field"><input type="checkbox" name="remove_datasheet" value="1">Hapus datasheet</label>@endif @endif</section>
<section class="form-section"><h2>Publikasi & SEO</h2><div class="form-grid"><div class="field"><label for="status">Status *</label><select name="status" id="status"><option value="draft" @selected(old('status', $entry->status) === 'draft')>Draft</option><option value="published" @selected(old('status', $entry->status) === 'published')>Published</option></select></div><x-field name="sort_order" type="number" label="Urutan" :value="$entry->sort_order ?? 0" required min="0" max="100000"/></div>@if($module === 'products')<label class="check-field"><input type="hidden" name="featured" value="0"><input type="checkbox" name="featured" value="1" @checked(old('featured', $entry->featured))>Tampilkan di beranda</label>@endif<x-field name="meta_title" label="SEO title" :value="$entry->meta_title" maxlength="200"/><x-field name="meta_description" label="Meta description" type="textarea" :value="$entry->meta_description" maxlength="500"/></section><div class="form-actions"><button class="button" type="submit"><x-icon name="save"/>Simpan {{ $config['label'] }}</button><a class="button secondary" href="{{ route('admin.catalog.index', $module) }}">Batal</a></div></form>
@endsection
